version: '3'

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file: .env
    networks:
      - default
      - proxy-tier

  weix_os:
    build: ./weix_os_app
    image: weix_os
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./weix_os_app/app:/var/www/weix_os
      - ./system_data:/var/www/weix_os/system_info
      - /mnt/live-drive:/var/www/weix_os/data
    env_file: .env
    networks:
      - default
      - proxy-tier
  

volumes:
  dbdata:

networks:
  proxy-tier:
    external:
      name: www-network
